Diplom/Diplom/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipe.urls')),
    path('info/', include('info.urls'))
] + static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Diplom/info/urls.py
from .views import rules, about
from django.urls import path

app_name = 'info'
urlpatterns = [
    path('rules/', rules, name='rules'),
    path('about/', about, name='about'),
]

Diplom/recipe/urls.py
from .views import index, detail, find_name, entry_name
from django.urls import path

app_name = 'recipe'
urlpatterns = [
    path('', index, name='index'),
    path('detail/<int:pk>/', detail, name='detail'),
    path('find_name/', find_name, name='find_name'),
    path('entry_name/', entry_name, name='entry_name'),
]

Diplom/info/models.py
from django.db import models

# Create your models here.

Diplom/recipe/models.py
from django.db import models


class Recipe(models.Model):
    name = models.CharField(max_length=100, verbose_name='Наименование блюда')
    describe = models.TextField(verbose_name='Описание')
    ingredients = models.TextField(verbose_name='Состав')
    steps = models.TextField(verbose_name='Способ приготовления')
    image = models.ImageField('foto', upload_to='recipe_img', blank=True)
    image1 = models.URLField('Дополнительное изображение', blank=True)

    def __str__(self):
        return f'{self.name}'

    class Meta:
        verbose_name = 'Рецепт'
        verbose_name_plural = 'Рецепты'
# Create your models here.

Diplom/info/views.py
from django.shortcuts import render


def rules(request):
    temp = 'info/rules.html'
    return render(request, temp)


def about(request):
    temp = 'info/about.html'
    return render(request, temp)
# Create your views here.

Diplom/recipe/views.py
from django.shortcuts import render
from .models import Recipe
from .form import FindName, EntryName

def index(request):
    temp = 'recipe/index.html'
    data = Recipe.objects.all()
    # print(data)
    context = {'names': data}
    return render(request, temp, context)


def detail(request, pk):
    temp = 'recipe/detail.html'
    object = Recipe.objects.get(id=pk)
    context = {'data': object}
    return render(request, temp, context)


def find_name(request):
    form = FindName(request.GET or None)
    if form.is_valid():
        name = request.GET['name']
        temp = 'recipe/detail.html'
        data = Recipe.objects.get(name=name)
        context = {'data': data}
        return render(request, temp, context)
    else:
        temp = 'recipe/find_name.html'
        form = FindName()
        context = {'form': form}
        return render(request, temp, context)


def entry_name(request):
    temp = 'recipe/entry_name.html'
    instance = None
    form = EntryName(request.POST or None, files=request.FILES or None, instance=instance)
    if form.is_valid():
        form.save()
    context = {'form': form}
    return render(request, temp, context)
# Create your views here.

Diplom/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">

    <title>
    {% block title %}
    {% endblock %}
    </title>
    {% load django_bootstrap5 %}
    {% bootstrap_css %}
</head>
<body>
    {%  include 'includes/header.html' %}
    <div class = "container pt-5">
    {% block content %}{% endblock %}
    </div>
    {%  include 'includes/footer.html' %}
</body>
</html>

Diplom/templates/includes/footer.html
<footer class="border-top text-center py-3">
    <h4>Company: &copy; Pavel</h4>
</footer>

Diplom/templates/includes/header.html
{% load static %}

<header>
      <nav class="navbar navbar-light" style="background-color: lightskyblue">
        <div class="container ">
          <a class="navbar-brand" href="{% url 'recipe:index' %}">
            <img src="{% static 'img/fav/logo-32x32.png' %}" width="30" height="30" class="d-inline-block align-top" alt="">
            Книга рецептов
          </a>
          <ul class="nav  nav-pills">
            <li class="nav-item">
              <a class="nav-link active" href="{% url 'recipe:index' %}">
                Главная
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'recipe:entry_name' %}">
                Добавить рецепт
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'recipe:index' %}">
                Каталог рецептов
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'recipe:find_name' %}">
                Поиск рецепта
              </a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'info:about' %}">
                Информация о сайте
              </a>
            </li>
            <li class="nav-item">

              <a class="nav-link" href="{% url 'info:rules' %}" >
                     Наши правила
              </a>

            </li>
          </ul>
        </div>
      </nav>
</header>

Diplom/templates/info/about.html
{% extends "base.html" %}

    {% block content %}
    <h3>Широкий выбор рецептов</h3>
    <p>Категории и фильтры: Рецепты обычно разделены
        на различные категории, такие как закуски, супы,
        основные блюда, десерты, вегетарианские и мясные
        блюда, что упрощает поиск нужных вариантов.
        Поиск по ингредиентам: Пользователи могут вводить
        доступные ингредиенты, и сайт предложит подходящие
        рецепты, что особенно удобно для тех, кто хочет
        использовать то, что есть в холодильнике.</p>
  {% endblock %}

Diplom/templates/info/info.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

Diplom/templates/info/rules.html
{% extends "base.html" %}

    {% block content %}
    <h6>Общие правила использования сайта</h6>
    <h5>Принятие условий</h5>
    <p>Используя наш сайт, вы соглашаетесь с настоящими правилами.
        Если вы не согласны с этими условиями, просьба не использовать сайт.</p>
    <h5>Регистрация и учетные записи</h5>
    <p>Для доступа к определённым функциям сайта может потребоваться регистрация.
        Пользователь несет ответственность за сохранность своих учетных данных и не имеет
        права передавать их третьим лицам. В случае подозрения на несанкционированный
        доступ к вашей учетной записи, необходимо немедленно уведомить администраторов
        сайта.</p>
    <h5>Использование контента</h5>
    <p>Вся информация, представленная на сайте, защищена авторским правом. Запрещается
        ее копирование и распространение без предварительного согласия правообладателей.
        Пользователи имеют право использовать материалы сайта только в личных и некоммерческих целях,
        если иное не указано.</p>
    <h5>Запрещенные действия</h5>
    <p>Запрещается использовать сайт для незаконной деятельности, в том числе, но не ограничиваясь,
        мошенничеством, кибербуллингом и распространением вредоносного ПО.
        Не допускается публикация оскорбительных, непристойных, угрожающих или
        дискриминационных материалов.</p>
    <h5>Конфиденциальность и защита данных</h5>
    <p>Пользовательская информация может собираться для улучшения работы сайта.
        Мы уважаем вашу конфиденциальность и не будем передавать ваши данные третьим
        лицам без вашего согласия, за исключением случаев, предусмотренных законом.</p>
    <h5>Изменения условий</h5>
    <p>Администрация оставляет за собой право в любой момент изменять условия использования сайта.
        Изменения будут опубликованы на этой странице, и ваше дальнейшее использование сайта будет
        означать, что вы принимаете обновленные условия.</p>
    <h5>Ответственность</h5>
    <p>Администрация сайта не несет ответственности за любой ущерб, возникший в результате использования
        сайта или невозможности его использования, включая, но не ограничиваясь, потерей данных или
        прибыли.</p>
    <h5>Контактная информация</h5>
    <p>В случае вопросов или проблем с использованием сайта, вы можете обратиться в службу поддержки через
        контактные формы или указанные адреса электронной почты.</p>
    <p>Эти правила создаются с целью обеспечения безопасного и комфортного использования сайта для всех пользователей.
        Рекомендуется ознакомиться с ними перед началом работы на площадке.</p>
  {% endblock %}

Diplom/templates/recipe/detail.html
{% extends "base.html" %}

    {% block content %}
    {% if data.image %}
        <img src="{{data.image.url}}" width="300" height="200" class="d-inline-block align-top" alt="">
    {% endif%}

    <h5><b>Описание:</b></h5><p>{{ data.describe}}</p>
    <h5><b>Состав:</b></h5><p>{{ data.ingredients }}</p>

  <h2>{{data.name}}</h2>
  <p>{{data.steps}}</p>
  {% endblock %}

Diplom/templates/recipe/entry_name.html
{% extends 'base.html' %}
  {% load django_bootstrap5 %}
  {% block title %} Добавить реквизиты
  {% endblock %}
  {% block content %}
    <h1>Добавить рецепт</h1>
    <main>
      <form method="POST" enctype="multipart/form-data" action="{% url 'recipe:entry_name' %}">
        {% csrf_token %}
        {% bootstrap_form form %}

        {% bootstrap_button button_type="submit" content="Добавить" %}

      </form>
    </main>
  {% endblock %}

Diplom/templates/recipe/find_name.html
{% extends 'base.html' %}
  {% load django_bootstrap5 %}
  {% block title %} poisk
  {% endblock %}
  {% block content %}
    <h1>Поиск</h1>
    <main>
      <form action="{% url 'recipe:find_name' %}">

        {% bootstrap_form form %}

        {% bootstrap_button button_type="submit" content="Поиск" %}

      </form>
    </main>
  {% endblock %}


<!--      {% with request.GET as data %}-->
<!--      {% if form.is_valid %}-->
<!--      <h2> {{inf}}</h2>-->
<!--      <h3>{{inf1}}</h3>-->
<!--      {% endif %}-->
<!--      {% endwith %}-->

Diplom/templates/recipe/index.html
{% extends "base.html" %}
{% load static %}

    {% block content %}
      <div class="container py-5">
        <h1>Список рецептов</h1>
        <!-- Перебираем в цикле все посты -->
        {% for i in names %}
        <hr>
        <article>
          <ul>
            <li>
              {% if i.image%}
                <img src="{{i.image.url}}" width="300" height="200" class="d-inline-block align-top" alt="">
              {% endif%}
            </li>
            <li>
              <h4>Блюдо: {{ i.name }}</h4>
            </li>
            <li>
              <h5><b>Описание:</b></h5>{{ i.describe|truncatewords:10 }}
            </li>
            <li>
              <h5><b>Состав:</b></h5>{{ i.ingredients }}
            </li>
            <li>
              <h5><b>Способ приготвления:</b></h5> {{ i.steps|truncatewords:30}}
            </li>
          </ul>          
          <!-- Первые 10 слов -->
          <p>
            {{i.text|truncatewords:10}}
          </p>
            <a href="{% url 'recipe:detail' i.id %}">Читать полный текст</a>

        </article>
        {% endfor %}


      </div>
  {% endblock %}